#!/bin/bash

# SPDX-FileCopyrightText: 2026 Duet LLC <contact@duet.llc>
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

STAGED_FILES=$(git diff --staged --name-only --diff-filter=ACMR)

STAGED_MOJO_FILES=$(echo "$STAGED_FILES" | grep '\.mojo$' || true)
if [ -n "$STAGED_MOJO_FILES" ]; then
  mojo format --quiet $STAGED_MOJO_FILES
  git add $STAGED_MOJO_FILES
fi

if [ -n "$STAGED_FILES" ]; then
  reuse lint-file --quiet $STAGED_FILES
fi

./test/run.sh
