# SPDX-FileCopyrightText: 2026 Duet LLC <contact@duet.llc>
#
# SPDX-License-Identifier: Apache-2.0

[workspace]
name = "mojo-uring"
version = "0.0.1"
description = "A high-performance async I/O library for Mojo"
authors = ["Duet LLC <contact@duet.llc>"]
license = "Apache-2.0"
repository = "https://github.com/duet-llc/mojo-uring"
channels = ["https://conda.modular.com/max-nightly/", "conda-forge"]
platforms = [
    { platform = "linux-64", linux = "5.1" },
    { platform = "linux-aarch64", linux = "5.1" },
]

[dependencies]
mojo = "==1.0.0b3.dev2026071505"
reuse = "6.2.0.*"
